### ISSUE TITLE
Definindo template da architecture Qbem

### ISSUE THREAD

**Issue by rrgaya** [qbem-repos/golang-arch-sample#1]
## TODO's

- [ ] Template de doc
  - [ ] API
  - [ ] Queue/Kafka/NatsIO ...N
  - [ ] Docker
  - [ ] Docker Compose
  - [ ] CI/CD Drone yml
  - [ ] Plugins VScode
  - [ ] Deploy
- [ ] Arch
  - [x] API
  - [x] Foo
    - [x] Entities
    - [x] Repos
      - [x] FooRepo
    - [x] UseCases
  - [ ] Schedules
    - [ ] Entities
    - [ ] Repos
    - [ ] UseCases
- [ ] Sandbox to Front End | Camilo
- [ ] Broadcast | ???
